CREATE TABLE users(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
